import { Inter } from "next/font/google";
import "./globals.css";
import HomeNavbar from "./components/navbar";
import { Footer } from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laxmi Pipe Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <HomeNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
